export const light = {
  body: "#EAEEF6",
  orangeText: "#FF6D00",
  purpleText: "#9A48F1",
  greenText: "#06B16E",
  grayText: "#ffffff",
  orangeBg: "#FFE4C2",
  purpleBg: "#E9D4FF",
  greenBg: "#B4FDD1",
  grayBg: "#94a6be",
  cardBg: "#ffffff",
  cardTitle: "#000000",
  headerUserClr: "#565eef",
  headerAColor: "#565eef",
  headerUserClrAfter: "solid #565eef",
  headerPopUserSetBg: "#ffffff",
  checkboxBg: "#eaeef6",
  checkboxBeforeBg: "#94A6BE",
  border: "#D4DBE5",
};

export const dark = {
  body: "#151419",
  orangeText: "#FFE4C2",
  purpleText: "#E9D4FF",
  greenText: "#B4FDD1",
  grayText: "#94a6be",
  orangeBg: "#FF6D00",
  purpleBg: "#9A48F1",
  greenBg: "#06B16E",
  grayBg: "#ffffff",
  cardBg: "#20202C",
  cardTitle: "#FFFFFF",
  headerUserClr: "#FFFFFF",
  headerAColor: "#ffffff",
  headerUserClrAfter: "solid #FFFFFF",
  headerPopUserSetBg: "#202229",
  checkboxBg: "#ffffff",
  checkboxBeforeBg: "#565EEF",
  border: "#4E5566",

};
